### ISSUE TITLE
Basic auth support

### ISSUE THREAD

**Issue by vito** [concourse/registry-image-resource#1]
Right now there's no way to configure auth, which means this resource is only useful for fetching public images.

There's all sorts of auth we'd need to support various registries. Let's start with the simplest one: basic auth.

**Comment by marco-m** [comment]
If I understand correctly now this resource supports basic auth, for example in https://github.com/concourse/concourse/blob/e5d5b9af1ef45243fe9062a86fe7392e74cd5f6a/ci/pipelines/concourse.yml#L714

    - name: unit-image
      type: registry-image
      source:
        repository: concourse/unit
        username: ((docker.username))
        password: ((docker.password))	

is this correct ?

**Comment by vito** [comment]
Right now it's only supported by `put` because I needed it for pushing to work at all. So `check` and `get` still can't use basic auth for private images.

**Comment by int-tt** [comment]
Thank you for a wonderful resource!
I needed to use a private repository in my work, so I tried writing PR:)  #9

**Comment by vito** [comment]
finished, tested, and documented!

thanks for the PR, @int-tt!
