### ISSUE TITLE
"put" step fails with error "x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by theenglishway** [concourse/registry-image-resource#10]
Hi,

I've been pulling my hairs off for a few days trying to get this resource type to pull/push to a local private Docker registry that I have setup. 

My setup is rather simple : 
* Concourse is run on my local machine (run under Debian) using the official Docker compose file (with a database, a web service, and a worker)
* The Docker registry is run on my local machine as well
* I made myself my own Certificate Authority and used this CA to generate my Docker registry's certificate 
* I accepted my own CA certificate by the usual `dpkg-reconfigure ca-certificates`

At this point things go pretty well : 
* From my local machine, using the docker CLI, I can push/pull to my local docker registry 
* From a machine on my LAN, I can push/pull as well (provided it has accepted the CA)
* From any container I run on my local machine, I can access my registry as well (provided I have updated the CAs in the containers) via curl (e.g. `curl https://time.home/v2/_catalog` returns the list of my repositories [`time.home` being my machine's hostname] )
* `concourse/builder` or `img` run "by hand" on my machine (via a `docker run`) can also push/pull to my local registry (provided their CAs have been updated of course)

Now, in Concourse, I have setup a very simple pipeline whose sole job is to build a docker image (using `concourse/builder` on a minimal workspace I build within one of the tasks) and push it to my local registry (using the resource type provided in this repo).

The build step goes great, the image is built, and then comes the final `put` stage, that always ends the same way : 

```
INFO[0000] pushing sha256:c1acdd46a1c94d8cd5349878ff567eea6efd1af2a272fdbbe29219cfde9bf15a to time.home/dummy-base: 
ERRO[0000] failed to upload image: Get https://time.home/v2/: x509: certificate signed by unknown authority 
```
I've been looking around everywhere for days trying to understand what was going on (having no experience with Docker, SSL, Concourse I didn't want to jump to conclusions), and I've found a hack that basically suits my limited needs, which is to generate beforehand my own Docker image of `concourse/registry-image-resource` updated with my own CA.

But my understanding is that it should work, even though I've read issues and PRs that make it look like a rather sensible subject (especially https://github.com/concourse/concourse/issues/1027), but nonetheless dealt with for such a basic case.

The [documentation](https://concourse-ci.org/implementing-resources.html#resource-certs) seems rather clear on the subject : 
> Certificates can be automatically propagated into each resource container, if the worker is configured to do so. 

So I've added my machine certs' dir in the worker's environment in docker-compose via `CONCOURSE_CERTS_DIR=/etc/ssl/certs/`, to no success. If I inspect the `put` step that fails, curl fails and there's no trace of my certificate in the `/etc/ssl/certs` : 

```
fly -t local i -j dummy-new/build-docker-base 
1: build #4, step: build-docker-image-base, type: task
2: build #4, step: build-workspace-base, type: task
3: build #4, step: dummy-image-base, type: put
choose a container: 3
bash-4.4# apk add curl
...
bash-4.4# curl https://time.home/v2/
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
bash-4.4# cat /etc/ssl/certs/ca-certificates.crt | grep QrnlfZjA1GyrEakJ1EXqWW32xQ9ZcSxFCjmebu8RPHBr4WGZZVRvltiWJ707PGdP
```
I can't even add it "by hand" within that container, since the /etc/ssl/certs is read-only (which seems to prove that the certificates are propagated indeed) : 

```
bash-4.4# update-ca-certificates 
Failed to open temporary file /etc/ssl/certs/bundleXXXXXX for ca bundl
bash-4.4# cat /usr/share/ca-certificates/theenglishway.crt >> /etc/ssl/certs/ca-certificates.crt 
bash: /etc/ssl/certs/ca-certificates.crt: Read-only file system
bash-4.4# mount
...
/dev/sda2 on /etc/ssl/certs type ext4 (ro,relatime,errors=remount-ro)
...
```
Among all the investigation I've made, I've noticed that using `update-ca-certificate` on a plain `alpine` image does not have the intended effect : 

```
$ docker run -ti -v $(pwd)/certs/ca/:/certs alpine 
/ # apk add ca-certificates curl
...
/ # cp /certs/ca.crt /usr/share/ca-certificates/ca.crt
/ # update-ca-certificates 
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
/ # curl https://time.home/v2/
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
Simply appending my certificate file makes it work : 
```
$ docker run -ti -v $(pwd)/certs/ca/:/certs alpine 
/ # apk add ca-certificates curl
...
/ # cat /certs/ca.crt >> /etc/ssl/certs/ca-certificates.crt 
/ # curl https://time.home/v2/_catalog
{"repositories":["alpine","docker-builder","dummy-base","dummy-full","image-builder","registry-image-resource"]}
```
This seems to be a [known issue](https://github.com/gliderlabs/docker-alpine/issues/30), and though it is marked as closed, it does not seem to be working so fine ... Could it be related ? 

I'll add that the whole pipeline works like a charm if I use a slightly updated image of `concourse/registry-image-resource` (with my CA embedded and "enabled"), and that the [legacy docker resource type](https://github.com/concourse/docker-image-resource) works fine in that regard as well, provided it's correctly setup (with `ca_certs`) ... It's painfully slow, though, so I'm glad I ended up finding @vito 's builder and registry-image-resource that work so much faster :+1: 

As I said I've been investigating this issue for days so maybe I've missed something obvious but now that I've found a rather clean workaround that fits my needs, I wanted to publicize this issue and get your thoughts about it

(BTW I might be able to share a git repo with the setup to reproduce this issue if needed, it just needs a bit of cleaning up)

**Comment by ademeglio** [comment]
@theenglishway @andyshinn

I've been having a similar problem that I've been struggling with for hours. For me, it's Docker in Docker and when I try to log into my gitlab registry, I get the x509 error. If I go to my CI server and docker login, I'm able to connect. Basically, the DIND is not updating the certificates.

I tried to create my own DIND image using docker:dind as the source container but I get the same error when trying to add the certificate. I know it's just a warning, but it seems to preventing any updates to the file. What I noticed is that if you `cat ca-certificates.crt` it seems to be missing the start tag for the first certificate (`----BEGIN CERTIFICATE-----`). I don't know enough about certs but I would think this would cause a problem.

**Comment by theenglishway** [comment]
@ademeglio I don't know much about certificates either, but that must certainly be a problem ! 

Have you tried the simple `cat <your ca.crt file> >> /etc/ssl/certs/ca-certificates.crt` that allowed it to work in my case ? 

If I've understood correctly, that's all `update-ca-certificates` or `dpkg-reconfigure ca-certificates` [on Debian systems] really does in the end, with a nice interface to pick the certificates you really trust and probably some checking of their consistency

**Comment by vito** [comment]
Strange that the cert propagation feature didn't work. Don't have much time
to look into this yet, but it should propagate as soon as the worker is
restarted with the new configuration and a new build is run.

Can't give precise instructions right now but you could try inspecting the
contents of the volume that was created for the workers certs; this is what
gets mounted into each resource container. I think you might be able to
locate this volume with `fly volumes -d` and then look under the volumes
path on the worker under the configured work-dir.

**Comment by ademeglio** [comment]
@theenglishway
Thank you for the response.

Yes, I came across another post somewhere that recommended to CAT my certificate into ca-certificates instead of the `update-ca-certificates` and also used the advice to create my own Docker in Docker image. Once I manually copied the contents of my cert into the ca-certificates.crt file in my Docker build for my modified DIND image, it started to work. 

I'm no expert, and unless I was reading the ca-certificates file incorrectly, the very first cert in the ca-certificates.crt file in the DIND Apline image seemed to be missing its start statement. Perhaps that is causing the `update-ca-certificates` propagation to fail?

Cheers,
Anthony

**Comment by apolegoshko** [comment]
Hi @ademeglio looks like I'm facing the same issue in core concourse image, but with get step. I'm build my own image using such dockerfile:
`FROM concourse/concourse:latest
ADD http://test.com/path/to/cert.crt /usr/local/share/ca-certificates
ADD http://test.com/path/to/cert1.crt /usr/local/share/ca-certificates
ADD http://test.com/path/to/cert2.crt /usr/local/share/ca-certificates
RUN update-ca-certificates
`
After build, I'm starting concourse using this command 
`docker run --name concourse -h concourse -p 8091:8080 --detach --privileged --restart=always --link concourse-db:concourse-db mybuildimage:latest quickstart --add-local-user=user:password --main-team-local-user=user --postgres-user=user --postgres-password=password --postgres-host=concourse-db --external-url=http://itoahdockerhostdev01.ops.server.lan:8091/
`
But I still cannot pull public images, which are stored in my private docker registry, getting the same error:
`* ping https: Get https://my-registry.test.com/v2/: x509: certificate signed by unknown authority`
