### ISSUE TITLE
Semver tags should be used for versions - not digests

### ISSUE THREAD

**Issue by vito** [concourse/registry-image-resource#151]
This has been brewing for a while. I hope to have more concrete details soon.

Over time there have been a few indicators that the versioning approach of this resource is a bit problematic, and we should instead find a reasonable way to interpret semver-like tags as versions, either instead of or in addition to digests (for purposes of detecting overwritten tags).

Digests are great for precisely identifying an image and detecting when a tag has changed, but pretending that a single tag represents a versioned history is a bit of a lie, since a tag can only really point to one digest, and doesn't contain information about prior digests that it pointed to.

Tags are often used semver-style, with a single repository having tags for e.g. `1.0.0`, `1.0.1`, `1.2.3` etc. This is in addition to tags like `1` and `1.0` which are "shorthand" allowing folks to refer to a semver "version line" without having to be precise. We'd have to figure out how to reconcile those too.

I'm opening this early so I can go back to it later and provide more concrete pain points around the current digest-based versioning scheme, but if you've run into any please leave them here too!

**Comment by vito** [comment]
Some context here: https://github.com/concourse/registry-image-resource/issues/48#issuecomment-517318523

It seems like this should help for situations where we're *pushing* new version tags. The current model forces you to configure a tag beforehand.

**Comment by vito** [comment]
We've been having a lot of trouble pushing tags properly, so it might be a good idea to have the resource do all the heavy lifting.

For example, let's say you have these tags published, with `=` notation here to show the same digest pushed to multiple tags:

* `6.0.0` = `6.0` = `6` = `latest`
* `5.3.1` = `5.3` = `5`
* `5.3.0`
* `5.2.0` = `5.2`

If I'm pushing version `5.2.1`, the resource could know to also push it as `5.2`.

If I'm pushing version `6.1.0`, the resource should know to also push it as `6.1`, `6` and `latest`.

If I'm pushing version `7.0.0`, the resource should know to also push it as `7.0`, `7`, and `latest`.

If I'm pushing version `6.1.1`, the resource should know to also push it as `6.1` and `6`.

**Comment by vito** [comment]
Another common convention is "variant" images, i.e. `6.1.2-alpine`, `6.1-alpine`, `6-alpine`, `alpine` (instead of `latest-alpine`). This is also sometimes done as a prefix rather than a suffix.

**Comment by vito** [comment]
When in this mode, it probably makes the most sense for `check` to only return the full three-part semver tags and not all the aliases. Otherwise the history is a moving target, with e.g. `6` constantly changing.

The mental model would be that `put` pushes the specific version you gave and just updates the other tags as "aliases".

**Comment by vito** [comment]
The [`traefik` repository](https://hub.docker.com/_/traefik) is an interesting case study.


Aside from that inconsistency, they have this pattern...:

They have tags like this...:

* `v2.2.1-windowsservercore-1809`
* `2.2.1-windowsservercore-1809`
* `v2.2-windowsservercore-1809`
* `2.2-windowsservercore-1809`
* `chevrotin-windowsservercore-1809`
* `windowsservercore-1809`

This kind of shows the existence of both "variant" tagging (`alpine`) and "latest aliases" (`chevrotin`), i.e. tags to also bump if the version being published is the latest available of the variant. "latest aliases" are annotated with the variant, and the variant tag itself is also pushed to on its own.

One thing to note is their `alpine` variant line *almost* follows this exact pattern, except their "naked" `alpine` tag hasn't been pushed since `1.7.16`, while the latest is `1.7.24`. I don't see a reason for that to be the case though. 🤔 I think this might show just how hard is is to get this right, haha.

They also don't seem to push just `1` and `2` versions - they stop at e.g. `1.7` and `2.2`.

They also push "variants" that have `v` in front of the semver versions, but this is a little awkward to treat like a "variant" because it shouldn't imply pushing `vwindowsservercore-1809`. To be honest I'm not really sure we want to worry about this lol.

**Comment by vito** [comment]
One thing to note since it might not be clear is that there's probably still a need for monitoring a specific tag for changes, e.g. the [`alpine` repository](https://hub.docker.com/_/alpine) has an `edge` tag which they probably push to all the time. They have "date tags" (i.e. `20200513`) but I don't really see an obvious way to tell the resource to monitor those specifically.

**Comment by vito** [comment]
The [`wordpress` repository](https://hub.docker.com/_/wordpress) is another interesting case since it has a *bunch* of variants that all effectively point to the same image:

> 5.4.1-apache, 5.4-apache, 5-apache, apache, 5.4.1, 5.4, 5, latest, 5.4.1-php7.3-apache, 5.4-php7.3-apache, 5-php7.3-apache, php7.3-apache, 5.4.1-php7.3, 5.4-php7.3, 5-php7.3, php7.3

Unpacking this, there are four variants:

* `apache`
* `php7.3`
* `php7.3-apache`
* (empty)

These are all the same image under the hood, but with different variants. I guess this could be done with four different resource definitions, or we would have a way to provide a list of variants or something.

**Comment by pn-santos** [comment]
Wonder if given the variants of tagging, the resource could have list of "well defined" tagging strategies (e.g. `semver`, `semver-variant`) and one would define the strategy when creating the resource definition.

Each strategy having it's own logic around tracking and pushing versions. And it might also require some extra params to properly configure it (and maybe also when doing `put`?)

Example:
```
resources:
- name: busy
  type: registry-image
  source:
    repository: busybox
    tagging_scheme: semver-variant
    variant: glibc
```

I think this would have the following advantages:
- The implementation (overall and of each strategy) might be simplified since each strategy would be simpler than supporting every tagging scheme under the sun
- Each strategy logic would be easier to document (vs documenting then entire possible ways of configuring the tagging scheme in a "one ~~ring~~ strategy to rule them all" scenario)
- It would be a nice way to maintain backwards compatibility (if no strategy is defined then current behaviour would prevail).
