### ISSUE TITLE
example pipeline with registry-image-resource

### ISSUE THREAD

**Issue by hejkerooo** [concourse/registry-image-resource#155]
As title mentions - I can't find anywhere how I can push to local docker registry my file (example)

**Comment by owenfarrell** [comment]
There's a skinny example in the [examples](https://github.com/concourse/examples/blob/master/pipelines/build-and-push-simple-image.yml) repository.

The one bit of magic is the `((image-repo-name))` variable. That value should resolve to the registry and repository (e.g. `hub.mycompany.net/adevteam`).

Might be worth pulling in that whole example in to this repo.
