### ISSUE TITLE
Support pushing images up to the registry

### ISSUE THREAD

**Issue by vito** [concourse/registry-image-resource#2]
We could really easily support pushing `docker save`d images, using these two methods:

* https://godoc.org/github.com/google/go-containerregistry/pkg/v1/tarball#ImageFromPath
* https://godoc.org/github.com/google/go-containerregistry/pkg/v1/tarball#Write

This would mesh really well with a Kaniko-based task for doing the actual building. Related: https://github.com/concourse/rfcs/issues/7 and https://github.com/concourse/docker-image-resource/issues/190#issuecomment-406321081

We'll probably need auth support for this first (#1).

**Comment by marco-m** [comment]
If I understand correctly there is preliminary support for pushing, for example in https://github.com/concourse/concourse/blob/master/ci/pipelines/concourse.yml:

      - put: unit-image
        params: {image: image/image.tar}

and the kaniko-based task is at https://github.com/concourse/builder, is this correct ?

**Comment by vito** [comment]
Yep, right now it's still experimental as I haven't worked out how we want to write tests for it yet, and I needed it sooner for our own pipeline in order for the `docker-image`-less pipeline experiment to continue.

The [`builder` task](https://github.com/concourse/builder) uses [`img`](https://github.com/genuinetools/img), but otherwise correct.

**Comment by vito** [comment]
added a test for pushing - thank goodness for [`random.Image`](https://godoc.org/github.com/google/go-containerregistry/pkg/v1/random#Image)!

there is still much to be desired, namely being able to dynamically specify additional tags, but i've at least documented what (little) is there

the README also references the `builder` task
