### ISSUE TITLE
check attempts to first check the 'registry_mirror', even when a registry-host-prefixed image is specified in the 'repository'

### ISSUE THREAD

**Issue by mdb** [concourse/registry-image-resource#247]
In current implementation, if a `registry_mirror` is configured, images whose `source.repository` contains a registry-host-prefixed image (such as `my-registry.com/foo/bar`) will still be first checked at the `registry_mirror` registry and _not_ the registry specified in the `repository` value. This cause 2 unwanted side effects...

* It generates excess requests against the `registry_mirror` in cases where the mirror does not mirror the registry whose host name is specified in the `repository` value, but instead mirrors a _different_ registry.
* I suspect it could fetch _the wrong_ image if the `registry_mirror` happens to host a namespace/image combination that collides with one hosted in the registry specified by the host-prefixed `repository`, but which is in fact a _different_ image altogether

This is especially problematic when a Concourse-wide [default registry has been configured](https://github.com/concourse/concourse/pull/6079). 

For example, given the following default `registry-image` configuration:

```yaml
registry-image:
  registry_mirror:
    host: my-default-mirror.com
```

...and the following `registry-image-resource`:

```yaml
- name: my-image
  type: registry-image
  source:
    repository: my-registry.com/foo/bar
```

...the resource attempts to _first_ check the image at `my-default-mirror.com/foo/bar`. Unless `my-default-mirror.com` is a mirror to `my-registry.com`, the `check` invocation may result in either excess requests to `my-default-mirror.com` or even an incorrect image resolution, as described above.

It's perhaps worth noting that this is not true of `docker` itself, which appears to successfully resolve `my-registry.com/foo/bar` from `my-registry.com`, even when `my-default-mirror.com` has been configured as a registry mirror. In the case of `docker`, it appears `my-registry.com/foo/bar` is successfully resolved without performing any requests to `my-default-mirror.com`.

This is similar to `docker-image-resource` [issue 305](https://github.com/concourse/docker-image-resource/issues/305)

**Comment by vito** [comment]
merged #248 - thanks!
