### ISSUE TITLE
How to check version of registry-image resource types?

### ISSUE THREAD

**Issue by eitah** [concourse/registry-image-resource#274]
We suspect we've been affected by this bug related to being unable to pass required docker credentials to publish docker files but because our pipeline yml's just import `type: registry-image` we can't see the specific resource image version tag we're using. I think it's correlated with our concourse version (6.7.1) but if so, can we bump the version of registry image resource manually or should we focus on getting onto latest of concourse? Alas `fly check-resource-type` doesn't have entries for registry-image resource.

bug in question: https://github.com/concourse/registry-image-resource/issues/269

**Comment by eitah** [comment]
We found the place where the  version is pinned! Thanks for dogfooding your own product much appreciated.  https://ci.concourse-ci.org/teams/main/pipelines/release-6.7.x/resources/registry-image-resource

**Comment by chenbh** [comment]
registry-image-resource (along with couple of others under the concourse org) is considered a base resource and is distributed along with Concourse worker itself. You should be able to hit the `/api/v1/workers` to get info on base resource type versions.

Note: for release 6.7.4 and up, we now record the bundled resource type versions in the [release notes itself](https://github.com/concourse/concourse/releases/tag/v6.7.4)
