### ISSUE TITLE
Version 1.3 causes "fetching the image did not produce a volume"

### ISSUE THREAD

**Issue by akshaymankar** [concourse/registry-image-resource#285]
All the checks fail with this error:

```
run check step: run check step: find or create container: fetching the image did not produce a volume
```

~Switching image tag to `1.3.1-alpine-20210629` fixes the problem. This means tags `1`, `1.3`, `1.3.1` and `1.3.1-alpine` are also broken as of now. I haven't tested with the ubuntu images.~

I am running concourse version `6.7.4`

**Comment by akshaymankar** [comment]
Maybe I was dreaming! This issue happens with `20210629` too. I could only fix it by going back to version `1.2.1`. I am not sure why this was working yesterday!

**Comment by clarafu** [comment]
@akshaymankar Are you still seeing this being an issue? If so, would you be able to provide the pipeline/resource/resource types that you are seeing this error on? Thanks!

**Comment by akshaymankar** [comment]
I don't see this issue anymore, I am not sure what was wrong. So I will close this issue.
