### ISSUE TITLE
Insecure registries not supported

### ISSUE THREAD

**Issue by designed4device** [concourse/registry-image-resource#29]
We can not switch from docker-image to registry-image due to insecure registries not being supported. Is there any plan to support insecure registries?

**Comment by vito** [comment]
There are *currently* no plans for this as I'm waiting to see where https://github.com/concourse/rfcs/issues/9 leads first. Alternatively to configuring "insecure", would you be able to configure CAs?

**Comment by designed4device** [comment]
Unfortunately, not within the scope of our control. They are working on upgrading to ssl, but have already been delayed twice and have not set a new date so who knows when that will happen.

**Comment by hemna** [comment]
I also am running into this problem.  I'm trying to learn concourse to build a docker image and push it into a private registry.   I added insecure_registries: [ "192.168.1.3:5000" ] to my registry-image resource and the pipeline fails when trying to put the image into the registry.

```
ERRO[0000] invalid payload: json: unknown field "insecure_registries" 
```

**Comment by oldgreen** [comment]
I also wanted to switch from docker-image to registry-image and this stopped me. I am using [WireGuard](https://www.wireguard.com/) to secure the communication with registry.

**Comment by tomjw64** [comment]
for those of use using docker-compose with local registries, is there a good way to migrate to using `registry-image-resource`?

**Comment by spiegela** [comment]
We need this feature to integrate with our organizations Artifactory registries.

**Comment by cherwin** [comment]
Hey @vito I was wondering what the status is on this issue? I appreciate that you're probably swamped. Most of us are. If you are able to give some pointers on how to allow insecure registries and If you think this change is do-able within a day or two, I'll happily jump in and contribute a fix.

**Comment by lintong** [comment]
Hi, when is this change due to be published?

**Comment by jamie-pate** [comment]
So happening on Linux with nvidia 1070. What version of the fix and is
there a setting to ensure it works?
