### ISSUE TITLE
Discussion item: Too many requests to a Google Cloud Registry

### ISSUE THREAD

**Issue by tanner-bruce** [concourse/registry-image-resource#3]
Hi there,

Occasionally we see issues with the docker image resource hitting our GCR too much causing us to get `429: Too many requests` responses while the resource is being checked, causing some 🍊s in our pipelines. I'm really not sure how to handle this (maybe using multiple registries?) but thought it would be worthwhile to bring up as a discussion point for the reimagining of the registry resource. 

Cheers, and thanks for the good work.

**Comment by vito** [comment]
One way we'll be cutting down on this across the board is to implement https://github.com/concourse/concourse/issues/2386 which will mean that equivalent resources across pipelines will only be checked once. So that'll help if you have a bunch of pipelines using the same images.
