### ISSUE TITLE
Support Private Authentication using Files

### ISSUE THREAD

**Issue by eedwards-sk** [concourse/registry-image-resource#30]
Feature Request:

Support reading username / password etc. from file

This would allow me to use ECR with a separate concourse task which does an `ecr:GetAuthorizationToken`, decodes it, and writes it to a file.

This also means private authentication would be supported for numerous providers without needing to add support into the resource itself.

**Comment by vito** [comment]
This won't help for `get` or `check` because they both can't read from the filesystem. I think we should just focus on https://github.com/concourse/concourse/issues/3023 for getting ECR credentials.
