### ISSUE TITLE
Specify different architectures

### ISSUE THREAD

**Issue by natto1784** [concourse/registry-image-resource#313]
I can't find any option to specify what arch to use. I'm running concourse on an aarch64-linux machine and can only run ARM64 images.

**Comment by rfpludwick** [comment]
+1 to this. Some registries have multiple archs available on a specific tag, but there's no way to tell which arch to pull, which means Concourse always pulls amd64.

**Comment by natto1784** [comment]
bump, also it should use the host architecture if left unspecified, i would look into go-containerregistry when i get time but im not a go developer. i just switched to woodpecker CI for now.

**Comment by natto1784** [comment]
https://github.com/concourse/registry-image-resource/pull/36
