### ISSUE TITLE
Proposal: don't let "check" step failed if `source.tag` not exist on registry server

### ISSUE THREAD

**Issue by SimonXming** [concourse/registry-image-resource#32]
In current implement, even you don't specify `source.tag`, `put` step still push the image to the default `latest` tag. 
Our user wants to avoid using `latest` tag and only keep versioned tag. In this case, registry-image `check` step will fail. Could you avoid this kind of failure in `registry-image-resource`?(the same case won't fail in `docker-image-resource`)

**Comment by vito** [comment]
👍 Makes sense!
