### ISSUE TITLE
Feature request: Support content trust while image pushing?

### ISSUE THREAD

**Issue by SimonXming** [concourse/registry-image-resource#41]
## What challenge are you facing?
There are requests from users to add content trust(similar function like `DOCKER_CONTENT_TRUST` and `DOCKER_CONTENT_TRUST_SERVER`) in registry-image-resource. So they could sign image with their Notary server in concourse pipeline.

## What would make this better?
Add content trust feature at resource level or library level. I noticed registry-resource is using `github.com/google/go-containerregistry` and it doesn't support content trust feature right now. I have created https://github.com/google/go-containerregistry/issues/461, not sure if this feature request will be accepted. 

## Are you interested in implementing this yourself?
Yes, but I should wait for https://github.com/google/go-containerregistry/issues/461.

**Comment by vito** [comment]
Interesting, let's keep an eye on the upstream issue for now. Sounds reasonable to me though I don't have a whole lot of experience with it. I'm assuming the change wouldn't be too invasive.

**Comment by SimonXming** [comment]
Hi @vito, `go-containerregistry` developer suggest implement it at resource-type level([Link](https://github.com/google/go-containerregistry/issues/461#issuecomment-497028546)). So I would start working on the code change recently. WDYT?

**Comment by SimonXming** [comment]
Hi @vito, Is that OK adding this feature?

**Comment by vito** [comment]
@SimonXming Sorry but I'm in a similar position to the folks upstream, not being familiar enough with it to say yes or no. For now I would suggest just forking and making the change and then I'll have a better idea of what's involved, whether it should remain a fork, or whether there's another approach we could take. Does that sound OK?

**Comment by SimonXming** [comment]
Hi @vito, could you review PR #43 when it's convenient for you? Thanks

**Comment by pivotal-jamie-klassen** [comment]
Fixed in #46
