### ISSUE TITLE
Avoid reference to deprecate 'build' task in readme

### ISSUE THREAD

**Issue by kdvolder** [concourse/registry-image-resource#66]
I found this in the readme:

> This resource does not and will never support building - only registry image pushing/pulling. Building should instead be done with something like the builder task (or anything that can produce OCI image tarballs).

When I follow the link under 'builder task' it leads me to some other page that says it is deprecated.

Maybe it is better to point directly to the thing that replaces deprecated builder task instead?

**Comment by vito** [comment]
fixed by https://github.com/concourse/registry-image-resource/pull/71
